packages:
  - ./
  - .playground/

catalogs:
  cli:
    '@antfu/eslint-config': ^6.7.3
    '@antfu/ni': ^27.0.1
    bumpp: ^10.4.0
    eslint: ^9.39.2
    tsdown: ^0.18.4
    typescript: ^5.9.3
    vite: ^7.3.1
  inlined:
    '@antfu/utils': ^9.3.0
  playground:
    nuxt: ^4.3.0
    vue: ^3.5.27
    vue-router: ^4.6.4
  types:
    '@types/node': ^24.10.9

ignoreWorkspaceRootCheck: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

shellEmulator: true
